aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
  - &when_deploy_prod
    when:
      event:
        - promote
      environment:
        - prod

kind: pipeline
type: docker
name: trigger only promote


steps:
  - name: test if
    image: golang
    commands:
      - echo "test"
      - if  "test" == "tst" ; then echo "false"; else echo "true"; fi;

  
  #- name: check var scope
  #  image: golang
  #  commands:
  #    - import ENV_VAR
  #    - echo $ENV_VAR

  - name: get files
    image: golang
    commands:
      - echo "check each variable then if yes get their latest files"
    when:
      event:
        - promote
      target:
        - tst

  - name: db deployment
    image: golang
    commands:
      - echo ${DB}
      - if ${DB} == "YES"; then echo "deploying db"; else echo "exiting";exit 1; fi;
    when:
      event:
        - promote
      target:
        - tst

  - name: adf deployment
    image: golang
    commands:
      - if [ "$ADF" == "YES" ]; then echo "deploying adf"; else exit 0; fi;
    when:
      event:
        - promote
      target:
        - tst

  - name: pbi
    image: golang
    commands:
     # - apt-get install dos2unix
#      - if  ${TEST} == 'DB' then echo "deploying now the database" elif ${TEST} == "ADF" then echo "deploying now adf" else echo "deploying both" fi
      - if [ "$PBI" == "YES" ]; then echo "deploying pbi"; else exit 0; fi;
    when:
      event:
        - promote
      target:
        - tst
  

trigger:
  branch:
  - main
