kind: pipeline
type: docker
name: main pipeline

steps:
  - name: hello world
    image: golang
    commands:
      - echo "hello world"

trigger:
  branch:
    - main
  event:
    include:
      - push
    exclude:
      - promote

---

kind: pipeline
type: docker
name: promote to tst

steps:
  - name: get files
    image: golang
    commands:
      - echo "check each variable then if yes get their latest files"

  - name: db deployment
    image: golang
    commands:
      - if [ ${DB,,} = "yes" ]; then echo "deploying db"; else echo "exiting";exit 0; fi;

  - name: adf deployment
    image: golang
    commands:
      - if [ ${ADF,,} = "yes" ]; then echo "deploying adf"; else echo "exiting";exit 0; fi;

  - name: pbi
    image: golang
    commands:
      - if [ ${PBI,,} = "yes" ]; then echo "deploying pbi"; else echo "exiting";exit 0; fi;

trigger:
  event:
    - promote
  target:
    - tst
