aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
  - &when_deploy_prod
    when:
      event:
        - promote
      environment:
        - prod

kind: pipeline
type: docker
name: trigger only promote


steps:
  - name: hi
    image: golang
    commands:
    - echo "hi there"
    - echo $TEST
    - echo ${TEST}

  - name: special
    image: golang
    commands:
      - apt-get install dos2unix
#      - if  ${TEST} == 'DB' then echo "deploying now the database" elif ${TEST} == "ADF" then echo "deploying now adf" else echo "deploying both" fi
      - if [ -z "$TEST" ]; then echo "variable is null" fi
    when:
      event:
        - promote
      target:
        - tst
  

trigger:
  branch:
  - main
