aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
  - &when_deploy_prod
    when:
      event:
        - promote
      environment:
        - prod

kind: pipeline
type: docker
name: trigger only promote


steps:
  - name: test if
    image: golang
    commands:
      - echo "test"
    #  - if  "test" == "tst" ; then echo "false"; else echo "true"; fi;

  - name: get files
    image: golang
    commands:
      - echo "check each variable then if yes get their latest files"
    when:
      event:
        - promote
      target:
        - tst

  - name: db deployment
    image: golang
    commands:
      - if [ ${DB} = "YES" ]; then echo "deploying db"; else echo "exiting";exit 0; fi;
    when:
      event:
        - promote
      target:
        - tst

  - name: adf deployment
    image: golang
    commands:
      - if [ ${ADF} = "YES" ]; then echo "deploying adf"; else echo "exiting";exit 0; fi;
    when:
      event:
        - promote
      target:
        - tst

  - name: pbi
    image: golang
    commands:
      - if [ ${PBI} = "YES" ]; then echo "deploying pbi"; else echo "exiting";exit 0; fi;
    when:
      event:
        - promote
      target:
        - tst
  

trigger:
  branch:
  - main
