aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
  - &when_deploy_prod
    when:
      event:
        - promote
      environment:
        - prod

kind: pipeline
type: docker
name: trigger only promote


steps:
  - name: test if
    image: golang
    commands:
      - echo "test"

  
  #- name: check var scope
  #  image: golang
  #  commands:
  #    - import ENV_VAR
  #    - echo $ENV_VAR

  - name: special
    image: golang
    commands:
     # - apt-get install dos2unix
#      - if  ${TEST} == 'DB' then echo "deploying now the database" elif ${TEST} == "ADF" then echo "deploying now adf" else echo "deploying both" fi
      - if [ -z "$TEST" ]; then echo "variable is null"; fi
    when:
      event:
        - promote
      target:
        - tst
  

trigger:
  branch:
  - main
