aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
        
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: show file
    image: golang
    commands:
    - ls
  
  - name: show only stage
    image: golang
    commands:
    - echo "only in stage"
    <<: *when_deploy_stage

trigger:
  branch:
  - main

---
aliases-deployment-triggers:
  - &when_deploy_stage
    when:
      event:
        - promote
      environment:
        - stage
  - &when_deploy_prod
    when:
      event:
        - promote
      environment:
        - prod

kind: pipeline
type: docker
name: trigger only promote


steps:
  - name: hi
    image: golang
    commands:
    - echo "hi there"
    - echo $TEST
  
  

trigger:
  event:
  - promote
  target:
  - test
