kind: pipeline
type: docker
name: test pipeline

steps:
  - name: show file
    image: golang
    commands:
    - ls

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: trigger only promote

steps:
  - name: hi
    image: golang
    commands:
    - echo "hi there"

trigger:
  event:
  - promote
  target:
  - test