kind: pipeline
type: docker
name: main pipeline

steps:
  - name: hello world
    image: golang
    commands:
      - echo "hello world"

trigger:
  branch:
    - main
  event:
    include:
      - push
    exclude:
      - promote

---

kind: pipeline
type: docker
name: add files to storage

steps:
  - name: check for components
    image: golang
    commands:
      - echo ${DRONE_TAG}

trigger:
  ref:
    include:
      - refs/tags/**

---

kind: pipeline
type: docker
name: promote to tst

steps:
  - name: get files
    image: golang
    commands:
      - echo "check each variable then if yes get their latest files"

  - name: db deployment
    image: golang
    commands:
      - if [ ${DB,,} = "yes" ]; then echo "deploying db"; else echo "exiting";exit 0; fi;

  - name: adf deployment
    image: golang
    environment:
      DRONE_SP_PASS:
        from_secret: drone_sp_pass
    commands:
      - if [ ${ADF,,} = "yes" ]; then ./drone_promotion/"Shell Scripts"/Deploy/deploy_adf.sh; else echo "exiting";exit 0; fi;

  - name: pbi
    image: golang
    commands:
      - if [ ${PBI,,} = "yes" ]; then echo "deploying pbi"; else echo "exiting";exit 0; fi;

trigger:
  event:
    - promote
  target:
    - tst
